name: github pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  workflow_dispatch:
    
permissions:
      contents: write


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: 12


      - run: npm install
      - run: npm run build
      
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RESUME_TOKEN }}
          publish_dir: ./public
          
